language: ruby
cache: bundler
gemfile: Gemfile
script:
  - bundle exec jekyll build
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.6

env:
  global:
  - 'SFTP_USER=[ydnwpmmy]'
  - 'SFTP_PASSWORD=[qybkok-fynxo6-fijniM]'
  - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs
       -T filename
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@ftp.ydn.wpm.mybluehost.me/home4/ydnwpmmy/public_html/madeslowly.xyz/gaitq/filename
