language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
  - landing-2.0
rvm:
- 2.6
env:
  global:
  - JEKYLL_ENV=production
notifications:
  email:
    recipients:
    - "$dev_email"
    on_success: always
    on_failure: always

  slack: $dev_slack

script:
- bundle exec jekyll build --config _config.yml

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
addons:
  ssh_known_hosts: "$HOST"
deploy:
  provider: script
  skip_cleanup: true
  script:
  - rsync -r $TRAVIS_BUILD_DIR/_site/ $USERNAME@$HOST:$PATH
  on:
    all_branches: true
