os: linux
arch: arm64-graviton2
group: edge
language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6
notifications:
  email:
    recipients:
    - arran@madeslowly.co.uk
    on_success: always
    on_failure: always
script:
- gem build slow-steps.gemspec
deploy:
  provider: rubygems
  api_key:
    secure: H4aA+D2zn4K22eXdSdyXIodDqOpk8ScANuNcg8RKMx7uJAwL/Wmef2BRQhHWQXOU9t2+c5xlhACrD8MJcMTgCHHwXfC59LpxMO+w4VDhV8pssELheTsf2X4xVizBHHUR7ZfLXf0R3pP1wFj3MJy1NhNGz5AfFf9acIdEUdsFIEpeKLiHr0BIS583egk9eAu7gCBq+4d5iPCKXD2ug0vaZScI2AW+TdDl8vJBTiIjcmFdjkwPZHWM3hpMNNsV8+OmHvkJ1XzDFH7PL/MTJtLhlwHGUZozB7vHz+DMHoO/TtutipnvUdgosAdfdcmgVY144+qkZs3EBKVzNPsX3X0afgR5WZ5fCfgoIUD/RUtFBnoG9U9hMmDJ5VacazYfgzSZ9QzZcIfFewDOLtaqOZjwX8wxEbByV7ScZbEuf3VHWME+tfsJPz7oBaDRmx+ZIy7zg/9AypcGgkaXY/8rXitYCK0Ram+4Ds9ziLI8vtSJNrVE0+/i4D2+Y2kRVs3TrhSsN6QR+URBL4O4Xf4nhvLiZY8cMe/5PwysT2dtSRpwS1FNY/pCzhH5jnX+fPFsDXy9ebHy3FM1NRWaxRlk2IQy4h6k/RB7zVN1SK+vYZU9UpZUsafmRBFFVwq11gJNP8P9OLEhnnlHbamzIU2Cqhud9y7cKKFIvznQ85GI6Kdc/jE=
  gem: slow-steps
  on:
    repo: madeslowly/slow-steps
  skip_cleanup: 'true'
