os: linux
arch: arm64-graviton2
group: edge
language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6
notifications:
  email:
    recipients:
    - arran@madeslowly.co.uk
    on_success: always
    on_failure: always

script:
  - gem install gem-release
  - gem bump patch --file version.rb -m "bump slow-steps gem [skip travis]"
  - git push https://$travis_public_repo_token@github.com/madeslowly/slow-steps.git HEAD:master
  - gem build slow-steps.gemspec

deploy:
  provider: rubygems
  api_key:
    secure: FWS2RI9GLpT8deoNj9t6NfEptLmxnRLelw5mF8STczOVIym8L5i2E180pfnnlfOMJRZk63rAWgcTkgHkIHX1ur+dZ25sxdInDHcrWi6IGCXDlFxTInJ+2MTP5Fy3gChEHV4V/9Sv9Zh3rtdQQ5upsqrlVV3sVoJV+WJ0RpUzWXDmON4Xe/iFZ7n/5tY79hx6Jgn8jVrlTVu6eLaVp9USp/ZQzvRSGEZssMC1KK8cY9T9TKR+5YUGabzMwEr33DJ2B3exdh90Zyb8aWO2fjwf+4fExrDw/LnbegQfDzO6FXRYgAZsruesPkKrxszH6hoeCCcvoEajy30/v5CFTNOvWN31ELM9RhECDi36FT90Nw/WFdyvZgcz4y1tqQTIz9H1pEIE3TDgqty6BXLJh+gdtv416qYgtOzlTiWSjkIOQ6ACnHLBDxg+++AaoSB119FapxMfQaHXX4T8wAXkOQ3y8qXgTQ0ABVkThFoAMpSxaUgC7vAb08wxRc9REBMf7EciFRtVMU37QZLDdjhqwkEOtpUIuQVfPF9xiLUHd84m+9BSG9HlRY6e++m0uztVRb0+jn5R3y+oPhkxGyEuu/m2LtL+QMoMoZJtJCFmHMQ85nW8+dehFN0LPKmsP0VSRUg13oT2GiKccVlxuMiZZ73KugB2S+TAf9TV43htE3wJgXU=
