addons:
  ssh_known_hosts: ydn.wpm.mybluehost.me

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d


language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6
env:
  global:
  - JEKYLL_ENV=production
notifications:
  email:
    recipients:
    - arran@madeslowly.co.uk
    on_success: always
    on_failure: always

script:
- chmod +x _scripts/build.sh
- _scripts/build.sh

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ssh-add $HOME/.ssh/deploy_rsa
    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site ydnwpmmy@ydn.wpm.mybluehost.me:public_html/madeslowly.xyz/gaitq/test
  on:
    branch: master
