
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d

addons:
  ssh_known_hosts:
    - ftp.ydn.wpm.mybluehost.me
    - ydn.wpm.mybluehost.me

language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6
env:
  global:
  - JEKYLL_ENV=production

notifications:
  email:
    recipients:
    - arran@madeslowly.co.uk
    on_success: always
    on_failure: always

script:
  - bundle exec jekyll build --config _config.yml

deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site ydnwpmmy@ydn.wpm.mybluehost.me:public_html/madeslowly.xyz/gaitq/test
  on:
    branch: master
