os: linux
arch: arm64-graviton2
group: edge
language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6
notifications:
  email:
    recipients:
    - arran@madeslowly.co.uk
    on_success: always
    on_failure: always
# before_script:
#   - openssl aes-256-cbc -k "$slow_steps_travis_key_pwd" -d -a -in slow_steps_travis_key.enc -out slow_steps_travis_key
#
#   - echo -e "Host github.com\n  IdentityFile slow_steps_travis_key" > ~/.ssh/config
#
#   - git remote set-url origin git@github.com:madeslowly/slow-steps.git
#   - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
#   > ~/.ssh/known_hosts
#




script:
- gem install gem-release
- gem bump patch --file version.rb
- git push https://$(travis_public_repo_token)@github.com/madeslowly/slow-steps.git
- gem build slow-steps.gemspec
deploy:
  provider: rubygems
  api_key:
    secure: FWS2RI9GLpT8deoNj9t6NfEptLmxnRLelw5mF8STczOVIym8L5i2E180pfnnlfOMJRZk63rAWgcTkgHkIHX1ur+dZ25sxdInDHcrWi6IGCXDlFxTInJ+2MTP5Fy3gChEHV4V/9Sv9Zh3rtdQQ5upsqrlVV3sVoJV+WJ0RpUzWXDmON4Xe/iFZ7n/5tY79hx6Jgn8jVrlTVu6eLaVp9USp/ZQzvRSGEZssMC1KK8cY9T9TKR+5YUGabzMwEr33DJ2B3exdh90Zyb8aWO2fjwf+4fExrDw/LnbegQfDzO6FXRYgAZsruesPkKrxszH6hoeCCcvoEajy30/v5CFTNOvWN31ELM9RhECDi36FT90Nw/WFdyvZgcz4y1tqQTIz9H1pEIE3TDgqty6BXLJh+gdtv416qYgtOzlTiWSjkIOQ6ACnHLBDxg+++AaoSB119FapxMfQaHXX4T8wAXkOQ3y8qXgTQ0ABVkThFoAMpSxaUgC7vAb08wxRc9REBMf7EciFRtVMU37QZLDdjhqwkEOtpUIuQVfPF9xiLUHd84m+9BSG9HlRY6e++m0uztVRb0+jn5R3y+oPhkxGyEuu/m2LtL+QMoMoZJtJCFmHMQ85nW8+dehFN0LPKmsP0VSRUg13oT2GiKccVlxuMiZZ73KugB2S+TAf9TV43htE3wJgXU=
# env:
#   matrix:
#     secure: lyJkvrP8FyzIdKY9yf1DRYSVB/Z5za4cI5WZCuGTpJ9Sbs4t0GzeEw+9FE6r0HlignnXS6lCc7dSZqQF/VkzvHckBPK4nrriwzo7oOX4JBAZQ5Ybt4dT4UTvi+FQZlrNTjqpIQnIdQctrp4Kz16Ag4ghn3boh7VmA9LoQo2TequtDaOqA/d0zMfKCLJPCpuake0IZC+Z9fJ8J8EiF2YafY3SFWQFnolj9Vuv+8mCn4DkYU84yUneaUv4ONytcMpYLrCQx+tYpxKKQQ1amyE36HjluNiJDXIiddVJpt3VuBI+1R6RAr0PvlOxREIgmIvZ/1ow7JqmB6rlbVDTO2SK1PwLiL05d6hqUAKd0/wkWkwe/y5YAiLVwacGSTFL44iP2NFfaHMdRi21fosuzTV3/2lvdjELSB+67T2b0f/I+OFfEz8owVdcThi/pmPfdIKxzY5gr/5ZEB7/maKiaJ9AdE8KXxj+867lDVo+s7jEKD8btJj8rlSeJ8ge2BNq5LOc+FwUMY2rYLlJHKaBs3dvs36UcJ1GanTwiQ3SupFdDQSR6vaOemkxqlffHhICdch3/JwmQPCj6TrzMnj13/MfKrJcWCnWadV8GKipwfqJIQGeLahLKnFv9LIYS2Zyt92cMavs2s9QZx1cOCfzDt7+YFX7ZFFknBhMW9MLc0L3Y/I=
